### ISSUE TITLE
Users with "." in their names are not allowed

### ISSUE THREAD

**Issue by samgoodgame** [DistrictDataLabs/partisan-discourse#17]
Odd error that doesn't allow periods in user names.

django.core.urlresolvers.NoReverseMatch: Reverse for 'detail' with arguments '('samuel.goodgame',)' and keyword arguments '{}' not found. 1 pattern(s) tried: ['(?P<slug>[\w-]+)/$']

**Comment by bbengfort** [comment]
@samgoodgame Didn't we fix this and you put in a pull request?
