### ISSUE TITLE
Repo doesn't have webhooks (for readthedocs.org)

### ISSUE THREAD

**Issue by samgoodgame** [DistrictDataLabs/partisan-discourse#21]
In order to have readthedocs.org update documentation alongside Github commits, we have to have webhooks set up. Instructions from readthedocs.org are here; I'd do it but I can't access the Partisan Discourse repo settings:
- Go to the “Settings” page for your project
- Click “Webhooks & Services”
- In the “Services” section, click “Add service”
- In the list of available services, click “ReadTheDocs”
- Check “Active”
- Click “Add service”

http://docs.readthedocs.io/en/latest/webhooks.html
https://developer.github.com/webhooks/creating/

**Comment by bbengfort** [comment]
@samgoodgame ok I'll take care of it.

**Comment by bbengfort** [comment]
And the webhook is active.
