### ISSUE TITLE
Label Description

### ISSUE THREAD

**Issue by bbengfort** [DistrictDataLabs/partisan-discourse#22]
Make it more clear what users are doing when they are annotating. 
- [x] add a description field to Label 
- [x] display label as popover in annotation 
- [x] get sam to add descriptions 
- [x] export label fixture 

Optional: add "neutral label"

**Comment by bbengfort** [comment]
@samgoodgame ok; it's on you now. I've created a help button that brings in a modal that looks as follows:

<img width="899" alt="screenshot 2016-08-29 21 33 12" src="https://cloud.githubusercontent.com/assets/745966/18072955/4372cfc6-6e30-11e6-99a1-1363098fcfb0.png">

**Comment by samgoodgame** [comment]
@bbengfort Okay-- I added labels. They follow this format: "Choose this label if, in your opinion, this document demonstrates a bias, sentiment, perspective, or agenda that mostly aligns with the __________ party." My goal was to create labels that were comprehensive (allow for different flavors of "leaning" in one political direction or another) but simple.

**Comment by bbengfort** [comment]
@samgoodgame looks good, added them to the fixtures.
